### ISSUE TITLE
Online Storage & Local Backups

### ISSUE THREAD

**Issue by RichInSQL** [potatoqualitee/froopyland-dr#12]
Not sure this falls under the home lab section, maybe a new section is needed, not really sure?!  What about a section for things like photo backups, how to continue backing up photos, where things like this currently go and how to if they want stop photos backing up.

People tend to know how to back photos up online and how things like OneDrive, Google Drive etc. work but if you don't have a spouse and are relying on your parents who might not be as tech savvy they might not know what OneDrive is or even how to get onto it or what is stored there? I know mine wouldn't.  

Same thing goes for things like a local NAS - what is on there, what the NAS is, how to get to it and how to get the important things off it then what to do with it once the things that are important are removed.

**Comment by potatoqualitee** [comment]
This is a great idea and needs to be addressed. Photos are so important, I'll make it a section on its own. I'd also forgotten about my NAS as well.

**Comment by RichInSQL** [comment]
If you would like me to create a PR and draft something around the Google Drive / Photos part - happy to do so.

**Comment by potatoqualitee** [comment]
yeah! that sounds great, thank you. Please add the section to the tech part 💯
