### ISSUE TITLE
Physical Things

### ISSUE THREAD

**Issue by Hanselljlh** [potatoqualitee/froopyland-dr#13]
If you have a safe or weapons of sorts.

You would think your spouse would have that info but there are circumstances all to often like mine. My spouse has severe depression thus CAN NOT have access to my safe or the backup weapon lock keys. So you can imagine what could happen if she got to them shortly after I went up state to play with the doggos.

My thought for NON ISSUE spouses that ARE ALLOWED to access these things (maybe just wanted nothing to do with whatever) if there is a digital lock or physical combination lock put that code into your password manager. If you have a physical key as primary or backup to the electronic lock; let them know where you hide it. In my case even explaining to them were it is you may have to add a photo in your password manager or email it to yourself not giving details as to what it is (some PM don't allow stoage). Then in the body put a specific string they can search for and find just that email. 

For CAN NOT HAVE DIRECT ACCESS spouse... I personally wouldn't trust anyone with my spare key or give them a code or the combination. So I would get a good small fireproof safe with a physical combination. Then email it to the person you trust and tell them never delete it cause blah blah reason. You can do the same search string thing for them but MAKE SURE YOU DELETE IT FROM YOUR SENT folder. Have spouse turn over the small safe at time of death, search string so they can find the email,  and instructions on what to do with the weapons. 

You can also add a layer of security and add maths to the combo on either or both safes. E.G. put a combo in the document that is not going to open the safe but until spouse contacts trustee the numbers are useless. The trustee will have an email with spouse's first digit plus 6 second digit pluse 1 third digit minus 5 which is the actual small safe combo. That gives you a degree of separation if say the government wants your guns and gets your death letter with the wrong combo. 

You can also change it so that spouse is notified that a person they know/know of will approch them upon ur death. So for further separation you can incude in ur FB Twitter announcement that if someone was sent an email you told them never to delete contact your spouse with the information. 

With that approach you can actually give multiple people different math problems with different key phrases they tell ur spouse and list which phrase is first access with backups down the line. Never know who is going to still be close to or out live you years from now. You can easily edit the list for your spouse if you need to add/remove or prioritize; instead of having to worry about fixing the list and getting a new trustee immediately if something happens to them.

**Comment by potatoqualitee** [comment]
Thank you @Hanselljlh! I will include a variation of your suggestion in an upcoming update.
